name: Electronic shop backend NestJS
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: setup environment
        env:
          DATABASE_USER: ${{ secrets.dbUser }}
          DATABASE_PASSWORD: ${{ secrets.dbPass }}
          DATABASE_HOST: ${{ secrets.dbHost }}
          DATABASE_PORT: ${{ secrets.dbPort }}
          DATABASE: ${{ secrets.dbName }}
        run: |
          echo $DATABASE_USER | base64 --decode > .env &&
          echo $DATABASE_PASSWORD | base64 --decode >> .env &&
          echo $DATABASE_HOST | base64 --decode >> .env &&
          echo $DATABASE_PORT | base64 --decode >> .env &&
          echo $DATABASE | base64 --decode >> .env

      - name: setup
        run: npm ci

      - name: Test
        run: npm test
